name: Deploy Blog FrontEnd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Navigate to your project directory on the server
            cd /home/manuel/blog-front

            # Pull the latest commit from the main branch
            git pull origin main

            # Install any new dependencies (use npm ci if you want a clean install)
            npm install

            # Build the project (adjust this if your build command is different)
            npm run build

            # Optionally, restart your application
            # For example, if you’re using pm2:
            pm2 reload all
