name: Deploy Blog FrontEnd

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Navigate to your project directory on the server
            cd /home/manuel/blog-front

            # Pull the latest commit from the main branch
            git pull origin master

            # Install any new dependencies
            npm install

            # Build the project
            npm run build

            # restart application
            pm2 reload all
